/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chessengine.java;

import javax.swing.*;
import java.awt.*;

public class App {

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.getContentPane().setBackground(Color.black);
        frame.setLayout(new GridBagLayout());
        frame.setMinimumSize(new Dimension(1000,1000));
        frame.setLocationRelativeTo(null);

        Board board = new Board();
        frame.add(board);

        frame.setVisible(true);
    }
}
